### ISSUE TITLE
Merge with existing user on new login

### ISSUE THREAD

**Issue by eknoes** [Kuestenschmiede/LdapBundle#1]
I am currently working on improvements for our current setup. We will switch to LDAP authentication, but already have >50 user accounts and groups with individual permissions that we can't represent as LDAP groups.

So I'd like to work on an option which merges the "new" LDAP Account with the existing user on their first login, based on an configurable field - we would use the mail address. I just want to hear if you see any problems on such a solution?

**Comment by maltedv** [comment]
The only difference will be the first login for LDAP users. Instead of creating a new user the user will be updated. Currently the updating of an existing user is working for the second login and above. Therefore I don't think that this should lead to any problems.

**Comment by eknoes** [comment]
I think it is finished and works fine! Thanks!
