### ISSUE TITLE
Allow ssl as encryption

### ISSUE THREAD

**Issue by dorianim** [Kuestenschmiede/LdapBundle#10]
https://github.com/Kuestenschmiede/LdapBundle/blob/7420be0736a5ff498a2cc531cff3b5d61af372d5/Resources/contao/dca/tl_c4g_ldap_settings.php#L148

Ssl is not allowed over here. Why?

**Comment by maltedv** [comment]
At the moment, the SSL encryption is not fully integrated. That's why it's commented out. As soon as the bundle is working with SSL, this will be activated.

**Comment by dorianim** [comment]
Worsk for me 😄 
I had to manually set it in the database, though.

**Comment by coastforge-mei** [comment]
Fixed in version 1.5.0
