### ISSUE TITLE
Input type of linkWithUserMail

### ISSUE THREAD

**Issue by dorianim** [Kuestenschmiede/LdapBundle#11]
https://github.com/Kuestenschmiede/LdapBundle/blob/db94a6f1d91f86da3513151936418c0f2f922181/Resources/contao/dca/tl_c4g_ldap_settings.php#L252

Shouldn't the type of this be `checkbox`?
![image](https://user-images.githubusercontent.com/30153207/148600977-5ffb7ff9-913a-4fd7-977d-913da423bbc9.png)

**Comment by maltedv** [comment]
Because of problems with MySQL databases, this was changed to a text field. I will have another look on the reason for the issue, so it can be changed back to checkbox type.

**Comment by coastforge-mei** [comment]
Fixed in version 1.5.0
