### ISSUE TITLE
Allow multiple administrator groups

### ISSUE THREAD

**Issue by dorianim** [Kuestenschmiede/LdapBundle#12]
Hey there,

It would be nice to have an option to define multiple administrator groups. We currently get this warning 
![Screenshot_2022-03-22-10-45-29_1920x1080](https://user-images.githubusercontent.com/30153207/159452684-a78ddf37-1c2c-4279-9b47-5da0dd46f3cf.png)
stating that at least one group, which is not an admin group, has access to the template editor and therefore has implicit admin access. If it was possible to define multiple admin groups, we could avoid this warning.

**Comment by coastforge-cro** [comment]
We will make changes so that multiple admin groups can be selected.

But I wonder: why don't you merge the two groups, which you want to be admin groups, together? Since both groups should be admin groups, both groups would have the same permissions anyway and there would be no difference between the two groups, therefore they could be merged. Or am I missing something?

**Comment by dorianim** [comment]
Thanks!

> why don't you merge the two groups

One of these groups is for "global admins", they have admin access in every tool we use. The other group is only for "website admin", they only have admin access in Contao. These are two different groups of people, so we can't really merge them.

**Comment by coastforge-cro** [comment]
> One of these groups is for "global admins", they have admin access in every tool we use. The other group is only for "website admins", they only have admin access in Contao. These are two different groups of people, so we can't really merge them.

Ah, I see. Makes perfect sense then. 

I will report back here as soon as I have finished creating a solution.

**Comment by coastforge-mei** [comment]
The change has been implemented for a while. Only today we were able to make the version.
